# Generated by Django 5.0.2 on 2024-03-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('acad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('module_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deadline', models.DateField()),
                ('marked', models.BooleanField()),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_by', to='api.academics')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('save', 'Save'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('deadline', models.DateField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.academics')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('urn', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.module')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students'),
        ),
    ]
