# Generated by Django 5.0.2 on 2024-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mail',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
