# Generated by Django 5.0.2 on 2024-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mail',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('project', 'marked_by')},
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('name', 'student')},
        ),
    ]
