# Generated by Django 5.0.2 on 2024-03-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_mail'),
    ]

    operations = [
      
        migrations.AddField(
            model_name='students',
            name='responsible_academics_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_academics_1', to='api.academics'),
        ),
        migrations.AddField(
            model_name='students',
            name='responsible_academics_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_academics_2', to='api.academics'),
        ),
        migrations.AlterField(
            model_name='students',
            name='mail',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('project', 'marked_by')},
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('name', 'student')},
        ),
    ]
