# Generated by Django 5.0.2 on 2024-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('convener_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='mail',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('project', 'marked_by')},
        ),
        migrations.AlterUniqueTogether(
            name='projects',
            unique_together={('name', 'student')},
        ),
    ]
