# Generated by Django 5.0.2 on 2024-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_students_responsible_academics_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='total_marks',
        ),
        migrations.AddField(
            model_name='mark',
            name='func_criteria',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='style_criteria',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='syntax_criteria',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
