# Generated by Django 5.0.2 on 2024-03-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_students_responsible_academics_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='responsible_academics_1',
        ),
        migrations.RemoveField(
            model_name='students',
            name='responsible_academics_2',
        ),
    ]
