# Generated by Django 5.0.2 on 2024-03-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_convener_students_responsible_academics_1_and_more'),
        ('api', '0004_students_responsible_academics_1_and_more'),
    ]

    operations = [
    ]
