# Generated by Django 5.0.2 on 2024-03-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_marks_mark_total_marks_mark_func_criteria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='func_criteria',
            new_name='functional_criteria',
        ),
    ]
