# Generated by Django 5.0.2 on 2024-03-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_students_responsible_academics_1_and_more'),
        ('api', '0006_alter_students_responsible_academics_1_and_more'),
    ]

    operations = [
    ]
