# Generated by Django 5.0.2 on 2024-03-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_students_responsible_academics_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='responsible_academics_1',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
