# Generated by Django 5.0.2 on 2024-03-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_convener_alter_students_responsible_academics_1'),
    ]

    operations = [
       
    ]
