# Generated by Django 5.0.2 on 2024-03-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_convener'),
    ]

    operations = [
       
    ]
