# Generated by Django 5.0.2 on 2024-03-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_convener'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
