# Generated by Django 5.0.2 on 2024-03-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_convener'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='projects',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
