# Generated by Django 5.0.2 on 2024-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_convener_alter_projects_marked'),
    ]

    operations = [
      
    ]
