# Generated by Django 5.0.2 on 2024-03-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_convener_rename_marks_mark_total_mark_and_more'),
    ]

    operations = [
       
    ]
