# Generated by Django 5.0.2 on 2024-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_convener'),
    ]

    operations = [
        
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
    ]
