# Generated by Django 5.0.2 on 2024-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_convener_alter_mark_unique_together'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='mark',
            name='deadline',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('project', 'marked_by')},
        ),
    ]
