# Generated by Django 5.0.2 on 2024-03-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_convener_alter_mark_deadline_and_more'),
    ]

    operations = [
      
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set(),
        ),
    ]
